"""
PageIndex - Document Structure Extraction Library.

Provides tools for extracting hierarchical structure from Markdown documents
generated by OCR.

Primary API:
  md_to_tree(md_path, ...)   — synchronous entry point
  _md_to_tree_async(...)     — async entry point

Deprecated entry points (page_index_main, page_index) have been removed.
"""

from .entry_points import _md_to_tree_async, config, md_to_tree
from .utils import ConfigLoader

__all__ = [
    "md_to_tree",
    "_md_to_tree_async",
    "config",
    "ConfigLoader",
]
